name: Serve Website with ngrok

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  serve-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python (for a simple HTTP server)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4d5A7T8bs3T/ngrok-stable-linux-amd64.tgz
        tar xvf ngrok-stable-linux-amd64.tgz
        sudo mv ngrok /usr/local/bin

    - name: Start Python SimpleHTTPServer and ngrok
      run: |
        cd ./your-website-directory
        python -m http.server 8080 &
        ngrok http 8080 --authtoken ${{ secrets.NGROK_AUTH_TOKEN }} > /tmp/ngrok.log &
        echo "Server started on port 8080"
        echo "ngrok is running"
        sleep 10 # Allow ngrok to initialize
        
        # Print ngrok public URL
        ngrok_url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "ngrok public URL: $ngrok_url"

        sleep infinity
